#cloud-config
package_update: true
packages:
  - python3
  - python3-pip
  - python3-venv
  - jq
  - curl
  - pbzip2
runcmd:
  - mkdir -p /home/ubuntu/id-log /home/ubuntu/.rally/benchmarks/data/nyc_taxis
  - curl -fL --retry 5 --retry-delay 5 -o /home/ubuntu/.rally/benchmarks/data/nyc_taxis/documents.json.bz2 https://storage.yandexcloud.net/download-resources-for-apatsev/documents.json.bz2
  - chown -R ubuntu:ubuntu /home/ubuntu/id-log /home/ubuntu/.rally
  - sudo -u ubuntu python3 -m venv /home/ubuntu/venv
  - sudo -u ubuntu /home/ubuntu/venv/bin/pip install --upgrade pip esrally
  - echo 'export PATH="$HOME/venv/bin:$PATH"' >> /home/ubuntu/.bashrc
