apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: chaos
  namespace: elastic
spec:
  version: 9.5.4
  count: 3
  elasticsearchRef:
    name: chaos
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              kibana.k8s.elastic.co/name: chaos
