apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: loadgen-network-delay
  namespace: load
spec:
  action: delay
  mode: all
  duration: 10m
  direction: both
  selector:
    namespaces:
      - load
    labelSelectors:
      app: loadgen
    nodeSelectors:
      topology.kubernetes.io/zone: ${ZONE}
  delay:
    latency: 500ms
    correlation: "0"
    jitter: 0ms
