apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: loadgen-network-loss
  namespace: load
spec:
  action: loss
  mode: all
  duration: 10m
  direction: both
  selector:
    namespaces:
      - load
    labelSelectors:
      app: loadgen
    nodeSelectors:
      topology.kubernetes.io/zone: ${ZONE}
  loss:
    loss: "30"
    correlation: "0"
