apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: loadgen-pod-kill
  namespace: load
spec:
  action: pod-kill
  mode: all
  selector:
    namespaces:
      - load
    labelSelectors:
      app: loadgen
    nodeSelectors:
      topology.kubernetes.io/zone: ${ZONE}
