apiVersion: v1
kind: Service
metadata:
  name: vminsert-nlb
  namespace: vmks
  annotations:
    yandex.cloud/load-balancer-type: internal
    yandex.cloud/subnet-id: NLB_SUBNET_ID
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.1.35
  selector:
    app.kubernetes.io/name: vminsert
  ports:
    - name: http
      port: 8480
      targetPort: 8480
